defaults:
  - override hydra/job_logging: custom
  - _self_

data: null
repo_id: EuropeanValuesProject/european_values_survey

include_evs_trend: false
include_evs_wvs: true
countries: null
country_groups: null
use_country_groups: true
focus: null
seed: 4242

# Using a subset of the questions
subset_csv: null
top_num_questions_in_subset: null

plotting:
  umap_neighbours: 100
  top_umap_importances: -1  # If -1, will use all questions
  ellipses: true
  ellipse_std: 0.5
  fast: false
  save_plot: true
  show_plot: true

optimisation:
  method: davies_bouldin
  intra_dist_factor: 10.0
  sample_size_per_group: null  # If null, will use the full dataset
  max_iterations: 100
  population_size: 10
  min_questions: 10
  max_questions: null  # If null, will use all questions
  n_jobs: -1

discriminative_training:
  model_type: xgboost
  n_estimators: 1000
  n_cross_val: 10
  n_jobs: -1
  bootstrap: false
  compute_importances: true

generative_training:
  test_samples_per_country: 100

evaluation:
  model_path: models/model.pkl
