defaults:
  - override hydra/job_logging: custom
  - _self_

data: null
repo_id: EuropeanValuesProject/european_values_survey

countries: null
country_groups: null
use_country_groups: true

plotting:
  umap_neighbours: 100
  top_umap_importances: 50
  ellipses: true
  ellipse_std: 1.0
  fast: false

optimisation:
  sample_size_per_group: 100
  max_iterations: 100
  population_size: 10
  min_questions: 50
  focus: null
  n_jobs: -1
