defaults:
  - override hydra/job_logging: custom
  - _self_

data: null
repo_id: EuropeanValuesProject/european_values_survey

include_evs_trend: false
include_evs_wvs: true
countries: null
country_groups: null
use_country_groups: true
focus: null
seed: 4242

plotting:
  umap_neighbours: 100
  top_umap_importances: -1  # If -1, will use all questions
  ellipses: true
  ellipse_std: 0.5
  fast: false
  save_plot: true
  show_plot: true

optimisation:
  method: davies_bouldin
  sample_size_per_group: null  # If null, will use the full dataset
  max_iterations: 1000
  population_size: 10
  min_questions: 3
  max_questions: null  # If null, will use all questions
  n_jobs: -1

training:
  # Model type options:
  # - xgboost
  # - logistic_regression
  # - support_vector_machine
  # - naive_bayes_gaussian
  # - naive_bayes_multinomial
  model_type: xgboost
  n_estimators: 1000  # Only relevant for tree-based models
  n_cross_val: 10
  n_jobs: -1
