defaults:
  - override hydra/job_logging: custom
  - _self_

data: null
repo_id: EuropeanValuesProject/european_values_survey
remove_europe_separating_questions: true

umap_neighbours: 20
top_umap_importances: 50

countries: null
country_groups: null
use_country_groups: true

ellipses: true
ellipse_std: 1.0
