defaults:
  - override hydra/job_logging: custom
  - _self_

data: null
repo_id: EuropeanValuesProject/european_values_survey

umap_neighbours: 100

use_country_groups: true

ellipses: true
ellipse_std: 1.0
